Repository WildCodeSchool/lyon-js-sept-2020-g1, pull requests merged in 2020-11, with the labels that each got.

#34 Home search bar
  package-lock.json
  package.json
  src/Components/Home.js
  src/Components/SearchBar.js
  src/index.js
Labels: Ready for prod

#36 add recipes by ingredients with axios
  .env
  .gitignore
  package-lock.json
  package.json
  src/Components/Home.js
  src/Components/NavbarIngredients.css
  src/Components/NavbarIngredients.js
  src/Components/SearchBar.js
Labels: Ready for prod

#38 Auto complete
  .env
  .gitignore
  src/Components/Home.js
Labels: Ready for prod

#39 Afficher recettes
  .env
  .env~dev
  src/Components/AffichageRecettes.js
  src/Components/Home.css
  src/Components/Home.js
Labels: Ready for prod

#41 Random recipes
  src/Components/Home.js
  src/Components/SearchBar.js
Labels: Ready for prod

#42 Display recipe
  src/App.js
  src/Components/AffichageRecettes.js
  src/Components/Home.js
  src/Components/Recipe.css
  src/Components/Recipe.js
  src/Components/SearchBar.js
Labels: Ready for prod

#43 Btn retour
  src/Components/Navbar.css
  src/Components/Navbar.js
  src/Components/Recipe.css
  src/Components/Recipe.js
Labels: Ready for prod

#44 Display recipe
  src/Components/Home.css
  src/Components/Recipe.css
  src/Components/Recipe.js
Labels: Ready for prod

#46 Btn retour
  src/Components/Navbar.js
Labels: Ready for prod

#58 Css about us
  public/images/Avatars/Brieuc.png
  public/images/Avatars/Christian.png
  public/images/Avatars/Gilles.png
  public/images/Avatars/Jean.png
  public/images/Avatars/Sabrina.png
  public/images/FondEcran.jpg
  public/images/Logo projet 2/Logo 500x500  px (1).gif
  public/images/Logo projet 2/Logo 500x500  px (1).png
  public/images/Logo projet 2/Logo animé 500x500  px.gif
  public/images/Logo projet 2/Logo5.gif
  public/images/Logo projet 2/logo3.png
  src/App.css
  src/Components/AboutUs.js
Labels: Ready for prod

#49 Btn retour
  src/Components/Navbar.js
Labels: Ready for prod

#60 add some css to Home
  src/Components/Home.css
  src/Components/Home.js
  src/Components/SearchBar.js
  src/pictures/Logo.png
  src/pictures/LogoAnim.gif
  src/pictures/background-small.jpg
  src/pictures/background.jpg
Labels: Ready for prod

#62 button back to top done
  src/Components/BackToTop.css
  src/Components/BackToTop.js
  src/Components/Home.js
Labels: Ready for prod

#61 create SearchContext which stores current results and ingredients
  src/App.js
  src/Components/Home.js
  src/Components/NavbarIngredients.css
  src/Components/NavbarIngredients.js
  src/Components/SearchBar.js
  src/contexts/SearchContext.js
Labels: Conflicts

#63 Share recipe
  package-lock.json
  package.json
  src/Components/AffichageRecettes.js
  src/Components/Home.js
  src/Components/Recipe.css
Labels: Ready for prod

#64 Favoris
  src/App.css
  src/App.js
  src/Components/AffichageRecettes.js
  src/Components/BackToTop.css
  src/Components/Favoris.js
  src/Components/Favorites.css
  src/Components/Favorites.js
  src/Components/Footer.js
  src/Components/Home.css
  src/Components/Home.js
  src/Components/Navbar.css
  src/Components/Recipe.css
  src/Components/Recipe.js
  src/contexts/FavoritesContext.js
  src/hooks/useLocalStorage.js
Labels: Ready for prod

#70 rectif fond d'ecran
  public/images/AboutUs.jpeg
  src/Components/AboutUs.js
Labels: Ready for prod

#71 update css
  src/Components/AffichageRecettes.js
  src/Components/Favorites.css
  src/Components/Footer.js
  src/Components/Home.css
  src/Components/Home.js
  src/Components/MailTo.js
  src/Components/Navbar.css
  src/Components/Recipe.css
  src/Components/Recipe.js
  src/Components/SearchBar.js
  src/pictures/Logo_transparent.png
Labels: Ready for prod

#73 Formulaire
  src/Components/Contact.css
  src/Components/Contact.js
Labels: Ready for prod

#69 Bouton urgence
  public/images/Logo projet 2/Logo.png
  src/Components/AboutUs.js
  src/Components/Navbar.css
  src/Components/Navbar.js
Labels: Ready for prod

#74 resolve footer
  src/Components/Contact.css
Labels: Ready for prod

#85 Fix for demo
  src/Components/SearchBar.js
  src/contexts/FavoritesContext.js
  src/contexts/SearchContext.js
Labels: Ready for prod

#86 Context filtres
  src/App.css
  src/App.js
  src/Components/SearchBar.js
  src/contexts/SearchContext.js
Labels: Ready for prod

#88 Fixed back to top.
  src/Components/BackToTop.js
Labels: Ready for prod

#87 update back-btn on Recipe component
  src/Components/Recipe.js
Labels: Ready for prod

#90 Fix research
  src/App.css
  src/Components/Favorites.css
  src/Components/Home.css
  src/Components/Navbar.css
  src/contexts/SearchContext.js
Labels: Ready for prod

#91 Commentaries
  package-lock.json
  package.json
  src/Components/Recipe.css
  src/Components/Recipe.js
  src/contexts/SearchContext.js
Labels: Ready for prod

#94 Footer
  src/App.js
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/Recipe.css
Labels: Ready for prod

#93 Formulaire
  src/Components/Contact.css
  src/Components/Contact.js
  src/Components/Favorites.css
  src/Components/MailTo.js
Labels: Ready for prod

#92 Asso vin
  public/images/vin.jpg
  src/Components/Recipe.js
Labels: Changes requested

#99 Update favorites
  src/Components/AffichageRecettes.js
  src/Components/Contact.css
  src/Components/Favorites.css
  src/Components/Favorites.js
  src/Components/Navbar.css
  src/Components/Navbar.js
  src/Components/SearchBar.js
  src/hooks/useLocalStorage.js
Labels: Ready for prod

#98 Add other ingredients required info
  src/Components/AffichageRecettes.js
  src/Components/Contact.css
  src/Components/Contact.js
  src/Components/Home.css
  src/Components/Home.js
  src/contexts/SearchContext.js
Labels: Ready for prod

#97 rectif padding wine card
  src/Components/Recipe.js
Labels: Ready for prod

#95 Responsive about us
  src/Components/AboutUs.js
Labels: Ready for prod

#89 Share recipe on social networks.
  src/Components/Recipe.css
  src/Components/Recipe.js
Labels: Fixed - ready for prod

#102 Commentaries
  src/Components/Recipe.css
  src/Components/Recipe.js
Labels: Ready for prod

#100 Send formulaire
  src/Components/Contact.js
  src/Components/ValidationMessage.js
Labels: Ready for prod

#104 fix error scroll to top unmount
  src/Components/BackToTop.js
Labels: Ready for prod

#111 Fixed brieuc
  src/Components/Footer.js
  src/Components/Home.js
Labels: Ready for prod

#109 Css recipe
  src/App.js
  src/Components/AboutUs.js
  src/Components/AffichageRecettes.js
  src/Components/Contact.css
  src/Components/Contact.js
  src/Components/Navbar.js
  src/Components/Recipe.css
  src/Components/Recipe.js
  src/Components/ScrollTop.js
  src/Components/Wine.js
Labels: Ready for prod

#108 Css logo
  src/Components/Home.css
  src/Components/Navbar.css
  src/Components/SearchBar.js
Labels: Ready for prod

#105 rectif size background
  src/Components/AboutUs.js
Labels: Ready for prod

#117 key index commentaries resolved
  src/Components/Home.js
  src/Components/Recipe.js
Labels: Ready for prod

#118 Last fix
  src/Components/AffichageRecettes.js
  src/Components/Contact.css
  src/Components/Contact.js
  src/Components/Home.css
Labels: Ready for prod
